name: Create Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run application to generate patients.json
        run: |
          # run the packaged jar to create patients.json
          java -jar target/pamscli-1.0-SNAPSHOT.jar || true

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/pamscli-1.0-SNAPSHOT.jar
          asset_name: pamscli-1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive

      - name: Upload patients.json to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: patients.json
          asset_name: patients.json
          asset_content_type: application/json
