name: Create Release on Tag

on:
  push:
    tags:
      - 'v*'

# Grant explicit permissions so the workflow can create releases using GITHUB_TOKEN
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    # Use a personal access token when available. Create a repo secret named RELEASE_TOKEN
    # with a PAT that has 'repo' scope if your organization blocks GITHUB_TOKEN from creating releases.
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch full history so tags are available
          fetch-depth: 0
          # keep the default token so subsequent steps can use it
          persist-credentials: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run application to generate patients.json
        run: |
          # run the packaged jar to create patients.json
          java -jar target/pamscli-1.0-SNAPSHOT.jar || true

      - name: Run verify RELEASE_TOKEN
        run: |
          echo "Checking repository access with the provided RELEASE_TOKEN..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" https://api.github.com/repos/adrewtran/cs489-lab2b)
          echo "HTTP status code: $STATUS"
          if [ "$STATUS" -ne 200 ]; then
            echo "RELEASE_TOKEN cannot access repository (HTTP $STATUS). Please ensure the PAT has 'repo' scope and is authorized for the organization (SSO)." >&2
            exit 1
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Release created by GitHub Actions for ${{ github.ref_name }}"

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/pamscli-1.0-SNAPSHOT.jar
          asset_name: pamscli-1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive

      - name: Upload patients.json to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: patients.json
          asset_name: patients.json
          asset_content_type: application/json
